# Generated by Django 2.0 on 2017-12-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0003_auto_20171206_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risktype',
            name='author',
        ),
    ]
