# Generated by Django 2.0 on 2017-12-07 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0004_remove_risktype_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='deleted_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
    ]
