# Generated by Django 2.0 on 2017-12-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0007_auto_20171208_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Number'), ('3', 'Date'), ('4', 'Enum')], default='1', max_length=1),
        ),
    ]
