# Generated by Django 2.0 on 2017-12-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0016_auto_20171208_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
