# Generated by Django 2.0.4 on 2018-04-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsaleslead',
            old_name='est_revenue_GBP',
            new_name='est_revenue_USD',
        ),
        migrations.RenameField(
            model_name='saleslead',
            old_name='est_revenue_GBP',
            new_name='est_revenue_USD',
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='owning_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salesaccounts.CREmployee'),
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='pm',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salesaccounts.CREmployee'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='owning_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='salesaccounts.CREmployee'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='salesaccounts.CREmployee'),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sector',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='region',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='sector',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
