# Generated by Django 2.0.4 on 2018-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_riskfield',
            new_name='user_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='contact',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
