# Generated by Django 2.0.4 on 2018-04-10 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0002_auto_20180410_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='actual_close_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='est_decision_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
