# Generated by Django 2.0 on 2017-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0002_auto_20171206_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risktype',
            name='name',
            field=models.CharField(default='jj', max_length=256),
            preserve_default=False,
        ),
    ]
