# Generated by Django 2.0.4 on 2018-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0002_auto_20180419_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='est_revenue_USD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='est_revenue_USD',
            field=models.FloatField(default=0),
        ),
    ]
