# Generated by Django 2.0.4 on 2018-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0004_auto_20180419_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleslead',
            name='next_action_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='next_action_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_top40',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='is_top40',
            field=models.BooleanField(default=False),
        ),
    ]
