# Generated by Django 2.0.4 on 2018-04-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0005_auto_20180419_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='is_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsaleslead',
            name='next_action_person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='salesaccounts.CREmployee'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='next_action_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='salesaccounts.CREmployee'),
        ),
    ]
