# Generated by Django 2.0 on 2017-12-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risktypes', '0005_risktype_deleted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskfield',
            options={'verbose_name': 'RiskField', 'verbose_name_plural': 'RiskFields'},
        ),
        migrations.AlterModelOptions(
            name='risktype',
            options={'verbose_name': 'RiskType', 'verbose_name_plural': 'RiskTypes'},
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='len_decim',
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='length',
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='name',
        ),
        migrations.RemoveField(
            model_name='riskfield',
            name='type',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='organization',
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risktype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risktype_riskfield', to='risktypes.RiskType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_riskfield', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risktype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_risktype', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
