# Generated by Django 2.0 on 2017-12-08 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0006_auto_20171207_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='enumlist',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='len_decim',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1e+30)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1e+65)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfield',
            name='type',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Date'), (4, 'Enum')], default=1, max_length=256),
        ),
        migrations.AddField(
            model_name='risktype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risktype',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
