# Generated by Django 2.0 on 2017-12-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0009_auto_20171208_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_risktype', to='risktypes.RiskType'),
        ),
    ]
