# Generated by Django 2.0.5 on 2018-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0011_auto_20180519_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='relationship_status',
            field=models.CharField(choices=[('3', 'Super'), ('2', 'Good'), ('1', 'Okay'), ('0', 'Worrying')], default='3', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='relationship_status',
            field=models.CharField(choices=[('3', 'Super'), ('2', 'Good'), ('1', 'Okay'), ('0', 'Worrying')], default='3', max_length=256),
        ),
    ]
