# Generated by Django 2.0.5 on 2018-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesaccounts', '0012_auto_20180519_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='relationship_status',
            field=models.CharField(choices=[('3', 'Super'), ('2', 'Good'), ('1', 'Okay'), ('0', 'Worrying')], default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='relationship_status',
            field=models.CharField(choices=[('3', 'Super'), ('2', 'Good'), ('1', 'Okay'), ('0', 'Worrying')], default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalsaleslead',
            name='next_action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='next_action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
