# Generated by Django 2.0 on 2017-12-08 16:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0018_auto_20171208_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='enum_values',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='is_nullable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='len_decim',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1e+30)]),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='length',
            field=models.IntegerField(default=256, validators=[django.core.validators.MaxValueValidator(1e+65)]),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='max_value',
            field=models.IntegerField(default=256, validators=[django.core.validators.MaxValueValidator(1e+65)]),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='min_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1e+65)]),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='type',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Date'), (4, 'Enum')], default=1, max_length=256),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
